title: Tech Blog
email: dev-danx@example.com
description: A tech blog by Dan
author: Dan
url: "https://dev-danx.github.io/techblog"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
