title: Tech Blog
email: dev-danx@example.com
description: A tech blog by Dan
author: Dan
url: "https://dev-danx.github.io/techblog"
baseurl: "/techblog"

# Build settings
markdown: kramdown
future: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
